/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "modules/arbiter/arbiter.v:1" *)
module arbiter(clk, rst, enb, empty_vchannel0, empty_vchannel1, empty_vchannel2, empty_vchannel3, arbiter_input, valid_channel, rndrobin_input);
  (* src = "modules/arbiter/arbiter.v:41" *)
  wire [1:0] _00_;
  (* src = "modules/arbiter/arbiter.v:41" *)
  wire [3:0] _01_;
  (* src = "modules/arbiter/arbiter.v:22" *)
  input [1:0] arbiter_input;
  (* src = "modules/arbiter/arbiter.v:15" *)
  input clk;
  (* src = "modules/arbiter/arbiter.v:18" *)
  input empty_vchannel0;
  (* src = "modules/arbiter/arbiter.v:19" *)
  input empty_vchannel1;
  (* src = "modules/arbiter/arbiter.v:20" *)
  input empty_vchannel2;
  (* src = "modules/arbiter/arbiter.v:21" *)
  input empty_vchannel3;
  (* src = "modules/arbiter/arbiter.v:17" *)
  input enb;
  (* init = 2'b00 *)
  (* src = "modules/arbiter/arbiter.v:24" *)
  output [1:0] rndrobin_input;
  (* src = "modules/arbiter/arbiter.v:16" *)
  input rst;
  (* init = 4'b0000 *)
  (* src = "modules/arbiter/arbiter.v:23" *)
  output [3:0] valid_channel;
  NOT _02_ (
    .A(empty_vchannel3),
    .Y(_01_[3])
  );
  NOT _03_ (
    .A(empty_vchannel2),
    .Y(_01_[2])
  );
  NOT _04_ (
    .A(empty_vchannel1),
    .Y(_01_[1])
  );
  NOT _05_ (
    .A(empty_vchannel0),
    .Y(_01_[0])
  );
  BUF _06_ (
    .A(arbiter_input[0]),
    .Y(_00_[0])
  );
  BUF _07_ (
    .A(arbiter_input[1]),
    .Y(_00_[1])
  );
  DFF _08_ (
    .C(clk),
    .D(_01_[0]),
    .Q(valid_channel[0])
  );
  DFF _09_ (
    .C(clk),
    .D(_01_[1]),
    .Q(valid_channel[1])
  );
  DFF _10_ (
    .C(clk),
    .D(_01_[2]),
    .Q(valid_channel[2])
  );
  DFF _11_ (
    .C(clk),
    .D(_01_[3]),
    .Q(valid_channel[3])
  );
  DFF _12_ (
    .C(clk),
    .D(_00_[0]),
    .Q(rndrobin_input[0])
  );
  DFF _13_ (
    .C(clk),
    .D(_00_[1]),
    .Q(rndrobin_input[1])
  );
endmodule
