/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */
`define esweightedroundrobin  1
(* top =  1  *)
(* src = "modules/roundrobin/roundrobin.v:2" *)
module roundrobin(clk, rst, enb, valid_channel, pop_vchannel0, pop_vchannel1, pop_vchannel2, pop_vchannel3, arbiter, wghtd_output);
  (* src = "modules/roundrobin/roundrobin.v:45" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  (* src = "modules/roundrobin/roundrobin.v:18" *)
  input [1:0] arbiter;
  (* src = "modules/roundrobin/roundrobin.v:15" *)
  input clk;
  (* src = "modules/roundrobin/roundrobin.v:17" *)
  input enb;
  (* src = "modules/roundrobin/roundrobin.v:19" *)
  input [3:0] pop_vchannel0;
  (* src = "modules/roundrobin/roundrobin.v:20" *)
  input [3:0] pop_vchannel1;
  (* src = "modules/roundrobin/roundrobin.v:21" *)
  input [3:0] pop_vchannel2;
  (* src = "modules/roundrobin/roundrobin.v:22" *)
  input [3:0] pop_vchannel3;
  (* src = "modules/roundrobin/roundrobin.v:16" *)
  input rst;
  (* src = "modules/roundrobin/roundrobin.v:23" *)
  input [3:0] valid_channel;
  (* init = 4'b0000 *)
  (* src = "modules/roundrobin/roundrobin.v:24" *)
  output [3:0] wghtd_output;
  NAND _184_ (
    .A(pop_vchannel1[0]),
    .B(valid_channel[1]),
    .Y(_118_)
  );
  NOT _185_ (
    .A(_118_),
    .Y(_119_)
  );
  NOT _186_ (
    .A(valid_channel[3]),
    .Y(_120_)
  );
  NOT _187_ (
    .A(pop_vchannel3[0]),
    .Y(_121_)
  );
  NOR _188_ (
    .A(_121_),
    .B(_120_),
    .Y(_122_)
  );
  NOR _189_ (
    .A(valid_channel[2]),
    .B(valid_channel[1]),
    .Y(_123_)
  );
  NOR _190_ (
    .A(valid_channel[3]),
    .B(valid_channel[0]),
    .Y(_124_)
  );
  NAND _191_ (
    .A(_124_),
    .B(_123_),
    .Y(_125_)
  );
  NAND _192_ (
    .A(_125_),
    .B(wghtd_output[0]),
    .Y(_126_)
  );
  NOR _193_ (
    .A(_126_),
    .B(valid_channel[3]),
    .Y(_127_)
  );
  NOR _194_ (
    .A(_127_),
    .B(_122_),
    .Y(_128_)
  );
  NOR _195_ (
    .A(_128_),
    .B(valid_channel[2]),
    .Y(_129_)
  );
  NOT _196_ (
    .A(valid_channel[0]),
    .Y(_130_)
  );
  NAND _197_ (
    .A(pop_vchannel2[0]),
    .B(valid_channel[2]),
    .Y(_131_)
  );
  NAND _198_ (
    .A(_131_),
    .B(_130_),
    .Y(_132_)
  );
  NOR _199_ (
    .A(_132_),
    .B(_129_),
    .Y(_133_)
  );
  NOR _200_ (
    .A(pop_vchannel0[0]),
    .B(_130_),
    .Y(_134_)
  );
  NOT _201_ (
    .A(_134_),
    .Y(_135_)
  );
  NOR _202_ (
    .A(arbiter[1]),
    .B(arbiter[0]),
    .Y(_136_)
  );
  NAND _203_ (
    .A(_136_),
    .B(valid_channel[0]),
    .Y(_137_)
  );
  NAND _204_ (
    .A(_137_),
    .B(valid_channel[1]),
    .Y(_138_)
  );
  NAND _205_ (
    .A(_138_),
    .B(_135_),
    .Y(_139_)
  );
  NOR _206_ (
    .A(_139_),
    .B(_133_),
    .Y(_140_)
  );
  NOR _207_ (
    .A(_140_),
    .B(_119_),
    .Y(_141_)
  );
  NOT _208_ (
    .A(arbiter[0]),
    .Y(_142_)
  );
  NOR _209_ (
    .A(arbiter[1]),
    .B(_142_),
    .Y(_143_)
  );
  NOR _210_ (
    .A(_134_),
    .B(arbiter[1]),
    .Y(_144_)
  );
  NOR _211_ (
    .A(_144_),
    .B(_143_),
    .Y(_145_)
  );
  NOR _212_ (
    .A(_145_),
    .B(_141_),
    .Y(_146_)
  );
  NAND _213_ (
    .A(arbiter[1]),
    .B(arbiter[0]),
    .Y(_147_)
  );
  NOT _214_ (
    .A(_147_),
    .Y(_148_)
  );
  NOT _215_ (
    .A(_122_),
    .Y(_149_)
  );
  NOT _216_ (
    .A(wghtd_output[0]),
    .Y(_150_)
  );
  NOT _217_ (
    .A(valid_channel[1]),
    .Y(_151_)
  );
  NOT _218_ (
    .A(valid_channel[2]),
    .Y(_152_)
  );
  NAND _219_ (
    .A(_152_),
    .B(_151_),
    .Y(_153_)
  );
  NAND _220_ (
    .A(_120_),
    .B(_130_),
    .Y(_154_)
  );
  NOR _221_ (
    .A(_154_),
    .B(_153_),
    .Y(_155_)
  );
  NOR _222_ (
    .A(_155_),
    .B(_150_),
    .Y(_156_)
  );
  NAND _223_ (
    .A(_156_),
    .B(_123_),
    .Y(_157_)
  );
  NAND _224_ (
    .A(_118_),
    .B(_130_),
    .Y(_158_)
  );
  NOR _225_ (
    .A(_131_),
    .B(valid_channel[1]),
    .Y(_159_)
  );
  NOR _226_ (
    .A(_159_),
    .B(_158_),
    .Y(_160_)
  );
  NAND _227_ (
    .A(_160_),
    .B(_157_),
    .Y(_161_)
  );
  NOR _228_ (
    .A(_134_),
    .B(valid_channel[3]),
    .Y(_162_)
  );
  NAND _229_ (
    .A(_162_),
    .B(_161_),
    .Y(_163_)
  );
  NAND _230_ (
    .A(_163_),
    .B(_149_),
    .Y(_164_)
  );
  NAND _231_ (
    .A(_164_),
    .B(_148_),
    .Y(_165_)
  );
  NAND _232_ (
    .A(arbiter[1]),
    .B(_142_),
    .Y(_166_)
  );
  NOR _233_ (
    .A(_128_),
    .B(_153_),
    .Y(_167_)
  );
  NAND _234_ (
    .A(_119_),
    .B(_152_),
    .Y(_168_)
  );
  NAND _235_ (
    .A(_168_),
    .B(_131_),
    .Y(_169_)
  );
  NOR _236_ (
    .A(_169_),
    .B(_167_),
    .Y(_170_)
  );
  NOR _237_ (
    .A(_170_),
    .B(_166_),
    .Y(_171_)
  );
  NOT _238_ (
    .A(enb),
    .Y(_172_)
  );
  NOR _239_ (
    .A(_172_),
    .B(rst),
    .Y(_173_)
  );
  NOT _240_ (
    .A(_173_),
    .Y(_174_)
  );
  NOR _241_ (
    .A(_174_),
    .B(_171_),
    .Y(_175_)
  );
  NAND _242_ (
    .A(_175_),
    .B(_165_),
    .Y(_176_)
  );
  NOR _243_ (
    .A(_176_),
    .B(_146_),
    .Y(_177_)
  );
  NOR _244_ (
    .A(_150_),
    .B(rst),
    .Y(_178_)
  );
  NOR _245_ (
    .A(_178_),
    .B(_173_),
    .Y(_179_)
  );
  NOR _246_ (
    .A(_179_),
    .B(_177_),
    .Y(_000_[0])
  );
  NOT _247_ (
    .A(pop_vchannel1[1]),
    .Y(_180_)
  );
  NOR _248_ (
    .A(_180_),
    .B(_151_),
    .Y(_181_)
  );
  NOT _249_ (
    .A(pop_vchannel3[1]),
    .Y(_182_)
  );
  NOR _250_ (
    .A(_182_),
    .B(_120_),
    .Y(_183_)
  );
  NAND _251_ (
    .A(_125_),
    .B(wghtd_output[1]),
    .Y(_001_)
  );
  NOR _252_ (
    .A(_001_),
    .B(valid_channel[3]),
    .Y(_002_)
  );
  NOR _253_ (
    .A(_002_),
    .B(_183_),
    .Y(_003_)
  );
  NOR _254_ (
    .A(_003_),
    .B(valid_channel[2]),
    .Y(_004_)
  );
  NAND _255_ (
    .A(pop_vchannel2[1]),
    .B(valid_channel[2]),
    .Y(_005_)
  );
  NAND _256_ (
    .A(_005_),
    .B(_130_),
    .Y(_006_)
  );
  NOR _257_ (
    .A(_006_),
    .B(_004_),
    .Y(_007_)
  );
  NOR _258_ (
    .A(pop_vchannel0[1]),
    .B(_130_),
    .Y(_008_)
  );
  NOT _259_ (
    .A(_008_),
    .Y(_009_)
  );
  NAND _260_ (
    .A(_009_),
    .B(_138_),
    .Y(_010_)
  );
  NOR _261_ (
    .A(_010_),
    .B(_007_),
    .Y(_011_)
  );
  NOR _262_ (
    .A(_011_),
    .B(_181_),
    .Y(_012_)
  );
  NOR _263_ (
    .A(_008_),
    .B(arbiter[1]),
    .Y(_013_)
  );
  NOR _264_ (
    .A(_013_),
    .B(_143_),
    .Y(_014_)
  );
  NOR _265_ (
    .A(_014_),
    .B(_012_),
    .Y(_015_)
  );
  NOR _266_ (
    .A(_001_),
    .B(_153_),
    .Y(_016_)
  );
  NOR _267_ (
    .A(_005_),
    .B(valid_channel[1]),
    .Y(_017_)
  );
  NOR _268_ (
    .A(_017_),
    .B(_181_),
    .Y(_018_)
  );
  NAND _269_ (
    .A(_018_),
    .B(_130_),
    .Y(_019_)
  );
  NOR _270_ (
    .A(_019_),
    .B(_016_),
    .Y(_020_)
  );
  NAND _271_ (
    .A(_009_),
    .B(_120_),
    .Y(_021_)
  );
  NOR _272_ (
    .A(_021_),
    .B(_020_),
    .Y(_022_)
  );
  NOR _273_ (
    .A(_022_),
    .B(_183_),
    .Y(_023_)
  );
  NOR _274_ (
    .A(_023_),
    .B(_147_),
    .Y(_024_)
  );
  NOR _275_ (
    .A(_003_),
    .B(_153_),
    .Y(_025_)
  );
  NAND _276_ (
    .A(_181_),
    .B(_152_),
    .Y(_026_)
  );
  NAND _277_ (
    .A(_026_),
    .B(_005_),
    .Y(_027_)
  );
  NOR _278_ (
    .A(_027_),
    .B(_025_),
    .Y(_028_)
  );
  NOR _279_ (
    .A(_028_),
    .B(_166_),
    .Y(_029_)
  );
  NOR _280_ (
    .A(_029_),
    .B(_024_),
    .Y(_030_)
  );
  NAND _281_ (
    .A(_030_),
    .B(_173_),
    .Y(_031_)
  );
  NOR _282_ (
    .A(_031_),
    .B(_015_),
    .Y(_032_)
  );
  NOT _283_ (
    .A(wghtd_output[1]),
    .Y(_033_)
  );
  NOR _284_ (
    .A(_033_),
    .B(rst),
    .Y(_034_)
  );
  NOR _285_ (
    .A(_034_),
    .B(_173_),
    .Y(_035_)
  );
  NOR _286_ (
    .A(_035_),
    .B(_032_),
    .Y(_000_[1])
  );
  NAND _287_ (
    .A(pop_vchannel1[2]),
    .B(valid_channel[1]),
    .Y(_036_)
  );
  NOT _288_ (
    .A(_036_),
    .Y(_037_)
  );
  NOT _289_ (
    .A(pop_vchannel3[2]),
    .Y(_038_)
  );
  NOR _290_ (
    .A(_038_),
    .B(_120_),
    .Y(_039_)
  );
  NAND _291_ (
    .A(_125_),
    .B(wghtd_output[2]),
    .Y(_040_)
  );
  NOR _292_ (
    .A(_040_),
    .B(valid_channel[3]),
    .Y(_041_)
  );
  NOR _293_ (
    .A(_041_),
    .B(_039_),
    .Y(_042_)
  );
  NOR _294_ (
    .A(_042_),
    .B(valid_channel[2]),
    .Y(_043_)
  );
  NAND _295_ (
    .A(pop_vchannel2[2]),
    .B(valid_channel[2]),
    .Y(_044_)
  );
  NAND _296_ (
    .A(_044_),
    .B(_130_),
    .Y(_045_)
  );
  NOR _297_ (
    .A(_045_),
    .B(_043_),
    .Y(_046_)
  );
  NOR _298_ (
    .A(pop_vchannel0[2]),
    .B(_130_),
    .Y(_047_)
  );
  NOT _299_ (
    .A(_047_),
    .Y(_048_)
  );
  NAND _300_ (
    .A(_048_),
    .B(_138_),
    .Y(_049_)
  );
  NOR _301_ (
    .A(_049_),
    .B(_046_),
    .Y(_050_)
  );
  NOR _302_ (
    .A(_050_),
    .B(_037_),
    .Y(_051_)
  );
  NOR _303_ (
    .A(_047_),
    .B(arbiter[1]),
    .Y(_052_)
  );
  NOR _304_ (
    .A(_052_),
    .B(_143_),
    .Y(_053_)
  );
  NOR _305_ (
    .A(_053_),
    .B(_051_),
    .Y(_054_)
  );
  NOT _306_ (
    .A(_039_),
    .Y(_055_)
  );
  NOT _307_ (
    .A(wghtd_output[2]),
    .Y(_056_)
  );
  NOR _308_ (
    .A(_155_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _309_ (
    .A(_057_),
    .B(_123_),
    .Y(_058_)
  );
  NAND _310_ (
    .A(_036_),
    .B(_130_),
    .Y(_059_)
  );
  NOR _311_ (
    .A(_044_),
    .B(valid_channel[1]),
    .Y(_060_)
  );
  NOR _312_ (
    .A(_060_),
    .B(_059_),
    .Y(_061_)
  );
  NAND _313_ (
    .A(_061_),
    .B(_058_),
    .Y(_062_)
  );
  NOR _314_ (
    .A(_047_),
    .B(valid_channel[3]),
    .Y(_063_)
  );
  NAND _315_ (
    .A(_063_),
    .B(_062_),
    .Y(_064_)
  );
  NAND _316_ (
    .A(_064_),
    .B(_055_),
    .Y(_065_)
  );
  NAND _317_ (
    .A(_065_),
    .B(_148_),
    .Y(_066_)
  );
  NOR _318_ (
    .A(_042_),
    .B(_153_),
    .Y(_067_)
  );
  NAND _319_ (
    .A(_037_),
    .B(_152_),
    .Y(_068_)
  );
  NAND _320_ (
    .A(_068_),
    .B(_044_),
    .Y(_069_)
  );
  NOR _321_ (
    .A(_069_),
    .B(_067_),
    .Y(_070_)
  );
  NOR _322_ (
    .A(_070_),
    .B(_166_),
    .Y(_071_)
  );
  NOR _323_ (
    .A(_071_),
    .B(_174_),
    .Y(_072_)
  );
  NAND _324_ (
    .A(_072_),
    .B(_066_),
    .Y(_073_)
  );
  NOR _325_ (
    .A(_073_),
    .B(_054_),
    .Y(_074_)
  );
  NOR _326_ (
    .A(_056_),
    .B(rst),
    .Y(_075_)
  );
  NOR _327_ (
    .A(_075_),
    .B(_173_),
    .Y(_076_)
  );
  NOR _328_ (
    .A(_076_),
    .B(_074_),
    .Y(_000_[2])
  );
  NAND _329_ (
    .A(pop_vchannel1[3]),
    .B(valid_channel[1]),
    .Y(_077_)
  );
  NOT _330_ (
    .A(_077_),
    .Y(_078_)
  );
  NOT _331_ (
    .A(pop_vchannel3[3]),
    .Y(_079_)
  );
  NOR _332_ (
    .A(_079_),
    .B(_120_),
    .Y(_080_)
  );
  NAND _333_ (
    .A(_125_),
    .B(wghtd_output[3]),
    .Y(_081_)
  );
  NOR _334_ (
    .A(_081_),
    .B(valid_channel[3]),
    .Y(_082_)
  );
  NOR _335_ (
    .A(_082_),
    .B(_080_),
    .Y(_083_)
  );
  NOR _336_ (
    .A(_083_),
    .B(valid_channel[2]),
    .Y(_084_)
  );
  NAND _337_ (
    .A(pop_vchannel2[3]),
    .B(valid_channel[2]),
    .Y(_085_)
  );
  NAND _338_ (
    .A(_085_),
    .B(_130_),
    .Y(_086_)
  );
  NOR _339_ (
    .A(_086_),
    .B(_084_),
    .Y(_087_)
  );
  NOR _340_ (
    .A(pop_vchannel0[3]),
    .B(_130_),
    .Y(_088_)
  );
  NOT _341_ (
    .A(_088_),
    .Y(_089_)
  );
  NAND _342_ (
    .A(_089_),
    .B(_138_),
    .Y(_090_)
  );
  NOR _343_ (
    .A(_090_),
    .B(_087_),
    .Y(_091_)
  );
  NOR _344_ (
    .A(_091_),
    .B(_078_),
    .Y(_092_)
  );
  NOR _345_ (
    .A(_088_),
    .B(arbiter[1]),
    .Y(_093_)
  );
  NOR _346_ (
    .A(_093_),
    .B(_143_),
    .Y(_094_)
  );
  NOR _347_ (
    .A(_094_),
    .B(_092_),
    .Y(_095_)
  );
  NOT _348_ (
    .A(_080_),
    .Y(_096_)
  );
  NOT _349_ (
    .A(wghtd_output[3]),
    .Y(_097_)
  );
  NOR _350_ (
    .A(_155_),
    .B(_097_),
    .Y(_098_)
  );
  NAND _351_ (
    .A(_098_),
    .B(_123_),
    .Y(_099_)
  );
  NAND _352_ (
    .A(_077_),
    .B(_130_),
    .Y(_100_)
  );
  NOR _353_ (
    .A(_085_),
    .B(valid_channel[1]),
    .Y(_101_)
  );
  NOR _354_ (
    .A(_101_),
    .B(_100_),
    .Y(_102_)
  );
  NAND _355_ (
    .A(_102_),
    .B(_099_),
    .Y(_103_)
  );
  NOR _356_ (
    .A(_088_),
    .B(valid_channel[3]),
    .Y(_104_)
  );
  NAND _357_ (
    .A(_104_),
    .B(_103_),
    .Y(_105_)
  );
  NAND _358_ (
    .A(_105_),
    .B(_096_),
    .Y(_106_)
  );
  NAND _359_ (
    .A(_106_),
    .B(_148_),
    .Y(_107_)
  );
  NOR _360_ (
    .A(_083_),
    .B(_153_),
    .Y(_108_)
  );
  NAND _361_ (
    .A(_078_),
    .B(_152_),
    .Y(_109_)
  );
  NAND _362_ (
    .A(_109_),
    .B(_085_),
    .Y(_110_)
  );
  NOR _363_ (
    .A(_110_),
    .B(_108_),
    .Y(_111_)
  );
  NOR _364_ (
    .A(_111_),
    .B(_166_),
    .Y(_112_)
  );
  NOR _365_ (
    .A(_112_),
    .B(_174_),
    .Y(_113_)
  );
  NAND _366_ (
    .A(_113_),
    .B(_107_),
    .Y(_114_)
  );
  NOR _367_ (
    .A(_114_),
    .B(_095_),
    .Y(_115_)
  );
  NOR _368_ (
    .A(_097_),
    .B(rst),
    .Y(_116_)
  );
  NOR _369_ (
    .A(_116_),
    .B(_173_),
    .Y(_117_)
  );
  NOR _370_ (
    .A(_117_),
    .B(_115_),
    .Y(_000_[3])
  );
  DFF _371_ (
    .C(clk),
    .D(_000_[0]),
    .Q(wghtd_output[0])
  );
  DFF _372_ (
    .C(clk),
    .D(_000_[1]),
    .Q(wghtd_output[1])
  );
  DFF _373_ (
    .C(clk),
    .D(_000_[2]),
    .Q(wghtd_output[2])
  );
  DFF _374_ (
    .C(clk),
    .D(_000_[3]),
    .Q(wghtd_output[3])
  );
endmodule
